# Generated by Django 3.1.3 on 2020-12-05 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerMenu', '0002_selleritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleritem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='selleritem',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
