# Generated by Django 3.1.3 on 2020-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerMenu', '0003_auto_20201205_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleritem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
