# Generated by Django 3.1.3 on 2020-12-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerMenu', '0004_selleritem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercategory',
            name='category_des',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellercategory',
            name='category_image',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
