# Generated by Django 3.1.3 on 2020-12-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerMenu', '0005_auto_20201223_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleritem',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selleritem',
            name='quantity',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
