# Generated by Django 3.1.3 on 2020-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerMenu', '0006_auto_20201224_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleritem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='selleritem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
