# Generated by Django 3.1.3 on 2020-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
