# Generated by Django 3.1.3 on 2020-12-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_is_shop_verfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_shop_verfied',
            new_name='is_shop_verified',
        ),
    ]
