# Generated by Django 3.1.3 on 2020-12-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201205_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='aadhaar_image',
            new_name='aadhaar_back_image',
        ),
        migrations.AddField(
            model_name='users',
            name='aadhaar_front_image',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='owner_image',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
