# Generated by Django 3.1.3 on 2020-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201214_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='floor_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='mall_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
