# Generated by Django 3.1.3 on 2020-12-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201216_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='shop_latitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='shop_longitude',
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
