# Generated by Django 3.1.3 on 2020-12-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201216_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='shop_area',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
