# Generated by Django 3.1.3 on 2020-12-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_emailcodeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aadhar_back_comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='aadhar_front_comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='fssai_comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gstin_comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='owner_comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='shop_comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
