# Generated by Django 3.1.3 on 2020-12-13 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=32)),
                ('state_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citylocation_created_by', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_state_id', to='bakerAdmin.states')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
