# Generated by Django 3.1.3 on 2020-12-20 06:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakerAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='state_code',
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('pin_code', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('city', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_city_id', to='bakerAdmin.cities')),
                ('created_by', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arealocation_created_by', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(limit_choices_to={'is_blocked': False, 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_state_id', to='bakerAdmin.states')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
