# Generated by Django 3.1.3 on 2020-12-23 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_image', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_image', models.CharField(blank=True, max_length=225, null=True)),
                ('aadhaar_front_image', models.CharField(blank=True, max_length=225, null=True)),
                ('aadhaar_back_image', models.CharField(blank=True, max_length=225, null=True)),
                ('gstin_image', models.CharField(blank=True, max_length=225, null=True)),
                ('fssai_image', models.CharField(blank=True, max_length=225, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ccomment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_box',
            },
        ),
    ]
