# Generated by Django 3.1.3 on 2020-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201223_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbox',
            name='message_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
